// authed
export const RECEIVE_ACCESS_TOKEN = 'RECEIVE_ACCESS_TOKEN';
export const RECEIVE_AUTHED_USER = 'RECEIVE_AUTHED_USER';
export const RECEIVE_LIKES = 'RECEIVE_LIKES';
export const RECEIVE_AUTHED_PLAYLISTS = 'RECEIVE_AUTHED_PLAYLISTS';
export const RECEIVE_AUTHED_FOLLOWINGS = 'RECEIVE_AUTHED_FOLLOWINGS';
export const APPEND_LIKE = 'APPEND_LIKE';
export const SET_LIKE = 'SET_LIKE';

// songs
export const REQUEST_SONGS = 'REQUEST_SONGS';
export const RECEIVE_SONGS = 'RECEIVE_SONGS';

// entities
export const RECEIVE_ENTITIES = 'RECEIVE_ENTITIES';

// reset
export const RESET_AUTHED = 'RESET_AUTHED';

// player
export const CHANGE_CURRENT_TIME = 'CHANGE_CURRENT_TIME';
export const CHANGE_SELECTED_PLAYLISTS = 'CHANGE_SELECTED_PLAYLISTS';
export const CHANGE_PLAYING_SONG = 'CHANGE_PLAYING_SONG';
export const TOGGLE_IS_PLAYING = 'TOGGLE_IS_PLAYING';

// environment
export const CHANGE_IS_MOBILE = 'CHANGE_IS_MOBILE';
export const CHANGE_WIDTH_AND_HEIGHT = 'CHANGE_WIDTH_AND_HEIGHT';

// song
export const REQUEST_SONG = 'REQUEST_SONG';
export const RECEIVE_SONG = 'RECEIVE_SONG';
// export const RECEIVE_SONG_COMMENTS = 'RECEIVE_SONG_COMMENTS';
